import {effects,DEFAULT_EFFECTS,LIMITS,saveEffect,validEffect,drawParticleEffect,beginParticleFrame,particleFrameStats,loadParticleSprites,particleSpriteStatus} from './particles.mjs';
import {CARTOON_EFFECTS,FX_STYLES} from './cartoon-fx-presets.mjs';
import {PIXEL_EFFECTS} from './pixel-fx-presets.mjs';
const library={...CARTOON_EFFECTS,...PIXEL_EFFECTS};
const presetCount=Object.keys(library).length,galleryPages=Math.ceil(presetCount/18);
export class ParticleEditor {
 constructor(){this.id='px-sword-sweep';this.draft=structuredClone(effects[this.id]);this.playing=true;this.time=0;this.quality=1;this.sheet=false;this.galleryPage=0;}
 stop(){cancelAnimationFrame(this.frame);}
 mount(root){
  this.stop();this.root=root;root.className='particle-editor';
  root.innerHTML='<div class="particle-toolbar"><label>Effect <select aria-label="Particle effect"></select></label><button data-action="new">New effect</button><button data-action="save">Save effect</button><button data-action="reset">Restore preset</button><button data-action="export">Export JSON</button><label>Import JSON <input type="file" accept=".json"></label></div><div class="particle-workspace"><section><canvas width="720" height="420" aria-label="Live particle preview"></canvas><button data-action="play">Pause</button><button data-action="restart">Restart</button><p>Fire and knocked-out stars are used in game. Rain is a study here; the existing gameplay rain stays unchanged.</p><p class="particle-status" role="status"></p></section><aside></aside></div>';
  loadParticleSprites();
  const $=s=>root.querySelector(s),select=$('select'),status=$('.particle-status');
  const intro=$('.particle-workspace section p');intro.className='particle-description';intro.textContent=this.draft.description||'Editable gameplay particle preset.';
  const performanceLabel=document.createElement('p');performanceLabel.className='particle-performance';intro.after(performanceLabel);
  const quality=document.createElement('select');quality.setAttribute('aria-label','Particle preview quality');for(const [name,value]of [['Full detail','1'],['Low detail','0.4'],['Reduced motion','reduced']])quality.append(new Option(name,value));quality.value=this.reducedMotion?'reduced':String(this.quality);quality.onchange=()=>{this.reducedMotion=quality.value==='reduced';this.quality=this.reducedMotion?.4:Number(quality.value);};$('.particle-toolbar').append(quality);
  const sheet=document.createElement('button');sheet.dataset.action='sheet';sheet.textContent=this.sheet?'Single effect':`Preset gallery (${presetCount})`;sheet.onclick=()=>{this.sheet=!this.sheet;sheet.textContent=this.sheet?'Single effect':`Preset gallery (${presetCount})`;};$('.particle-toolbar').append(sheet);
  const pages=document.createElement('span');pages.className='particle-gallery-pages';for(const [label,delta]of [['‹',-1],['›',1]]){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-label',delta<0?'Previous effect gallery page':'Next effect gallery page');b.onclick=()=>{this.galleryPage=(this.galleryPage+delta+galleryPages)%galleryPages;this.time=0;};pages.append(b);}$('.particle-toolbar').append(pages);
  const binding=document.createElement('select');binding.setAttribute('aria-label','Gameplay particle slot');for(const id of ['torch','knockout','splash','jump-splash','arrow-splash','swim-wake','salvage-hands','salvage-burst','purple-aura','purple-eyes','pink-sparkle'])binding.append(new Option(DEFAULT_EFFECTS[id].name,id));
  const apply=document.createElement('button');apply.textContent='Apply to gameplay slot';apply.dataset.action='bind';apply.onclick=()=>{try{const value=structuredClone(this.draft);value.loop=['torch','knockout','purple-aura','purple-eyes','pink-sparkle'].includes(binding.value);saveEffect(binding.value,value);status.textContent='Applied to '+binding.selectedOptions[0].textContent+' · saved on this computer.';}catch(e){status.textContent=e.message;}};
  const restore=document.createElement('button');restore.textContent='Restore gameplay slot';restore.dataset.action='restore-binding';restore.onclick=()=>{saveEffect(binding.value,DEFAULT_EFFECTS[binding.value]);status.textContent='Gameplay slot restored.';};$('.particle-toolbar').append(binding,apply,restore);
  const groups=new Map();for(const [id,v]of Object.entries(effects).sort((a,b)=>a[1].name.localeCompare(b[1].name))){const name=id.startsWith('px-')?`Pixel FX · ${Object.keys(PIXEL_EFFECTS).length}`:id.startsWith('fx-')?`Cartoon FX · ${Object.keys(CARTOON_EFFECTS).length}`:'Gameplay / custom';let group=groups.get(name);if(!group){group=document.createElement('optgroup');group.label=name;select.append(group);groups.set(name,group);}group.append(new Option(v.name,id));}select.value=this.id;
  select.onchange=()=>{this.id=select.value;this.draft=structuredClone(effects[this.id]);this.time=0;this.mount(root);};
  const controls=$('aside');
  const field=(key,label,type,options)=>{const row=document.createElement('label');row.textContent=label;const input=document.createElement(options?'select':'input');if(options)for(const v of options)input.append(new Option(v,v));else input.type=type;input.value=this.draft[key];if(LIMITS[key]){const [min,max,step]=LIMITS[key];Object.assign(input,{min,max,step});}if(key==='name')input.maxLength=60;input.setAttribute('aria-label',label);input.oninput=()=>{const value=type==='number'?Number(input.value):input.value;const next={...this.draft,[key]:value};if(validEffect(next)){this.draft=next;status.textContent='Unsaved · preview updated';}else status.textContent='Enter a value within the shown limits.';};row.append(input);controls.append(row);};
  field('name','Name','text');for(const [key,label]of Object.entries({count:'Particle count',life:'Lifetime (seconds)',speedX:'Horizontal speed',speedY:'Vertical speed',spread:'Emitter width',gravity:'Gravity',size:'Size',orbit:'Orbit radius'}))field(key,label,'number');field('shape','Shape','text',['square','star','streak',...(this.draft.fx?['sprite']:[])]);if(this.draft.fx)field('fx','Composition','text',FX_STYLES);field('blend','Blend','text',['source-over','lighter']);field('start','Start color','color');field('end','End color','color');
  const action=(id,fn)=>$(`[data-action="${id}"]`).onclick=()=>{try{fn();}catch(e){status.textContent=e.message;}};
  action('save',()=>{saveEffect(this.id,this.draft);select.selectedOptions[0].textContent=this.draft.name;status.textContent='Saved · available next time you open the editor'+(['torch','knockout'].includes(this.id)?' and applied in game.':'.');});
  action('new',()=>{this.id='custom-'+Date.now().toString(36);this.draft={...structuredClone(this.draft),name:'New particle effect'};effects[this.id]=structuredClone(this.draft);this.time=0;this.mount(root);});
  action('reset',()=>{this.draft=structuredClone(DEFAULT_EFFECTS[this.id]||DEFAULT_EFFECTS.torch);this.mount(root);$('.particle-status').textContent='Preset restored in preview. Save to apply.';});
  action('play',()=>{this.playing=!this.playing;$('[data-action="play"]').textContent=this.playing?'Pause':'Play';});$('[data-action="play"]').textContent=this.playing?'Pause':'Play';
  action('restart',()=>{this.time=0;});
  action('export',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(this.draft,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=this.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  $('input[type=file]').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>20000)throw Error('Effect file is too large.');const v=JSON.parse(await f.text());if(!validEffect(v))throw Error('Invalid effect file.');this.draft=v;this.mount(root);$('.particle-status').textContent='Imported into preview. Save to apply.';}catch(e){status.textContent=e.message;}};
  const canvas=$('canvas'),c=canvas.getContext('2d');let previous;
  const tick=t=>{if(!root.isConnected)return;const dialog=root.closest('dialog');if(dialog&&!dialog.open)return;if(previous!==undefined&&this.playing)this.time+=Math.min(.05,(t-previous)/1000);previous=t;c.fillStyle='#102822';c.fillRect(0,0,720,420);beginParticleFrame(c,{budget:this.sheet?768:400,quality:this.quality,reducedMotion:this.reducedMotion});const started=performance.now();
    if(this.sheet){let i=0;for(const effect of Object.values(library).slice(this.galleryPage*18,this.galleryPage*18+18)){const x=60+i%6*120,y=60+Math.floor(i/6)*140;c.save();c.translate(x,y);c.scale(.6,.6);drawParticleEffect(c,effect,0,0,this.time%(effect.life+.3),i);c.restore();c.fillStyle='#e3f1d9';c.font='10px system-ui';c.textAlign='center';c.fillText(effect.name,x,y+62,115);i++;}}
    else{c.save();c.translate(360,this.draft.fx?210:this.id==='rain'?10:310);const scale=this.draft.fx?1.8:this.id==='rain'?1.7:3;c.scale(scale,scale);if(this.id==='torch'){c.fillStyle='#766046';c.fillRect(-3,-1,6,22);}drawParticleEffect(c,this.draft,0,0,this.draft.fx?this.time%(this.draft.life+.35):this.time);c.restore();}
    if(t-(this.lastStats||0)>250){const stats=particleFrameStats(c);performanceLabel.textContent=`${this.sheet?'Gallery '+(this.galleryPage+1)+'/'+galleryPages+' · ':''}${stats.draws} / ${stats.budget} particle draws · ${(performance.now()-started).toFixed(2)} ms CPU submission · ${particleSpriteStatus().loaded}/16 cartoon textures ready`;this.lastStats=t;}
    this.frame=requestAnimationFrame(tick);};this.frame=requestAnimationFrame(tick);
 }
}
