import test from 'node:test';import assert from 'node:assert/strict';
import {Game,EVENTS} from '../src/core.mjs';import {iceWorld,iceMotion,tickSnow,interactIce,ICE_PROPS} from '../src/ice-world.mjs';import {navigateEnemy} from '../src/navigation.mjs';import {waterAt} from '../src/environment.mjs';import {saveSession,restoreSession} from '../src/session.mjs';
const game=env=>{const g=new Game();g.environment=env;g.addPlayer('keyboard');g.start();g.openingBoard=false;g.scenery=[];return g;};
test('ice has distinct winter scenery and a contiguous frozen lake',()=>{const w=iceWorld(42);assert.ok(w.scenery.every(p=>ICE_PROPS.includes(p.kind)));for(const kind of ICE_PROPS)assert.ok(w.scenery.some(p=>p.kind===kind),kind);for(let y=10;y<18;y++)for(let x=10;x<17;x++)assert.equal(w.terrain[y*50+x],'ice');});
test('ice builds momentum, coasts on release, brakes with snow, and stops on snow terrain',()=>{const g=game('ice'),p=g.players[0];p.x=432;p.y=448;for(let i=0;i<20;i++)iceMotion(g,p,1,0,133,.05);assert.ok(p.slideX>100);const drift=iceMotion(g,p,0,0,133,.05).dx;assert.ok(drift>0);const v=p.slideX;g.snowDepth=1;const snowDrift=iceMotion(g,p,0,0,133,.05).dx;assert.ok(snowDrift<v*.05);g.terrain.fill('snow');assert.equal(iceMotion(g,p,0,0,133,.05).dx,0);assert.equal(p.slideX,0);});
test('blizzard only starts on ice, builds slowing snow, and persists in saves',()=>{const i=EVENTS.findIndex(e=>e.type==='blizzard');assert.ok(i>=0);for(const env of ['house','forest','desert']){const g=game(env);g.spawnEvent(i);assert.equal(g.weather,null);}const g=game('ice');g.spawnEvent(i);tickSnow(g,22);assert.equal(g.snowDepth,1);const p=g.players[0];p.x=600;p.y=600;g.moveActor(p,40,0);assert.ok(p.x<630);const restored=restoreSession(JSON.parse(JSON.stringify(saveSession(g))));assert.equal(restored.snowDepth,1);assert.equal(restored.weather.type,'blizzard');g.weather=null;tickSnow(g,150);assert.equal(g.snowDepth,0);});
test('winter berries and supplies can each be gathered once',()=>{const g=game('ice'),p=g.players[0];p.x=500;p.y=500;for(const kind of ['frost_shrub','winter_cache']){g.scenery=[{kind,x:500,y:490,size:40}];const count=g.loot.length;assert.equal(interactIce(g,p),true);assert.equal(g.loot.length,count+1);assert.equal(interactIce(g,p),false);}});
test('lion prowls when locked out, then routes through open doors to its target',()=>{const g=game('house');g.terrain.fill('grass');const lion={kind:'lion',x:1200,y:800,speed:85,hp:100,state:'hunt'},p={x:900,y:904};const initial={x:lion.x,y:lion.y};for(let i=0;i<50;i++){g.time+=.05;navigateEnemy(g,lion,p,.05);}assert.ok(Math.hypot(lion.x-initial.x,lion.y-initial.y)>50,'prowls outside');g.house.doors[1].open=true;g.house.doors[5].open=true;for(let i=0;i<450;i++){g.time+=.05;navigateEnemy(g,lion,p,.05);}assert.ok(Math.hypot(lion.x-p.x,lion.y-p.y)<60,JSON.stringify(lion));});
test('house walls and furniture stop feet at visible edges; players can enter exact-bound pools',()=>{const g=game('house'),p=g.players[0];g.terrain.fill('grass');p.x=540;p.y=450;g.moveActor(p,0,100);assert.ok(Math.abs(p.y-472)<3,p.y);p.x=560;p.y=560;g.moveActor(p,0,40);assert.ok(p.y<=568&&p.y>=565,p.y);g.house.pools=[{x:900,y:242,w:250,h:158}];assert.equal(waterAt(g,901,241),'grass');assert.equal(waterAt(g,901,243),'water');assert.equal(waterAt(g,1151,300),'grass');p.x=1000;p.y=220;g.moveActor(p,0,100);assert.ok(Math.abs(p.y-320)<.01);});
